"""empty message

Revision ID: 317d7a1793a7
Revises: 
Create Date: 2019-12-19 11:57:01.500140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '317d7a1793a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goodtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('good_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('good', sa.Column('goodtype_id', sa.Integer(), nullable=True))
    op.drop_index('ix_good_good_type', table_name='good')
    op.create_foreign_key(None, 'good', 'goodtype', ['goodtype_id'], ['id'])
    op.drop_column('good', 'good_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('good_type', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'good', type_='foreignkey')
    op.create_index('ix_good_good_type', 'good', ['good_type'], unique=False)
    op.drop_column('good', 'goodtype_id')
    op.drop_table('account')
    op.drop_table('goodtype')
    # ### end Alembic commands ###
