"""empty message

Revision ID: 8361b7b15640
Revises: 
Create Date: 2019-12-09 20:11:52.324326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8361b7b15640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consigner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=600), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('general_good', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=320), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=True),
    sa.Column('backup', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consigner_timestamp'), 'consigner', ['timestamp'], unique=False)
    op.create_table('driver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=600), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('car_type', sa.String(length=64), nullable=True),
    sa.Column('car_number', sa.String(length=64), nullable=True),
    sa.Column('transport_type', sa.String(length=255), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=True),
    sa.Column('backup', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_timestamp'), 'driver', ['timestamp'], unique=False)
    op.create_table('good',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('good_name', sa.String(length=255), nullable=False),
    sa.Column('good_type', sa.String(length=255), nullable=True),
    sa.Column('transport_origin', sa.String(length=255), nullable=False),
    sa.Column('transport_des', sa.String(length=255), nullable=False),
    sa.Column('transport_money', sa.String(length=255), nullable=True),
    sa.Column('good_status', sa.String(length=120), nullable=True),
    sa.Column('backup', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('consigner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consigner_id'], ['consigner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_good_good_name'), 'good', ['good_name'], unique=False)
    op.create_index(op.f('ix_good_good_type'), 'good', ['good_type'], unique=False)
    op.create_index(op.f('ix_good_timestamp'), 'good', ['timestamp'], unique=False)
    op.create_index(op.f('ix_good_transport_des'), 'good', ['transport_des'], unique=False)
    op.create_index(op.f('ix_good_transport_origin'), 'good', ['transport_origin'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result', sa.String(length=120), nullable=True),
    sa.Column('backup', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_result'), 'application', ['result'], unique=False)
    op.create_index(op.f('ix_application_timestamp'), 'application', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_timestamp'), table_name='application')
    op.drop_index(op.f('ix_application_result'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_good_transport_origin'), table_name='good')
    op.drop_index(op.f('ix_good_transport_des'), table_name='good')
    op.drop_index(op.f('ix_good_timestamp'), table_name='good')
    op.drop_index(op.f('ix_good_good_type'), table_name='good')
    op.drop_index(op.f('ix_good_good_name'), table_name='good')
    op.drop_table('good')
    op.drop_index(op.f('ix_driver_timestamp'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_consigner_timestamp'), table_name='consigner')
    op.drop_table('consigner')
    # ### end Alembic commands ###
