"""empty message

Revision ID: 138dba2faaa0
Revises: 638af9267c25
Create Date: 2019-12-04 14:49:57.299340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138dba2faaa0'
down_revision = '638af9267c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('backup', sa.String(length=255), nullable=True))
    op.add_column('consigner', sa.Column('backup', sa.String(length=255), nullable=True))
    op.add_column('driver', sa.Column('backup', sa.String(length=255), nullable=True))
    op.add_column('good', sa.Column('backup', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'backup')
    op.drop_column('driver', 'backup')
    op.drop_column('consigner', 'backup')
    op.drop_column('application', 'backup')
    # ### end Alembic commands ###
